import { builtinModules, createRequire, isBuiltin } from "node:module";
import { dirname, isAbsolute, join, relative } from "node:path";
import { realpathSync } from "node:fs";
import type { Plugin } from "vite";
import { nodeSpecifiers } from "./node-specifiers.mjs";
import { checkNodeUsage } from "./node-policy.js";

const aliases = new Map(nodeSpecifiers.flatMap((entry) => [[entry.name, entry.target], [`node:${entry.name}`, entry.target]]));
const builtins = new Set(builtinModules.map((name) => name.replace(/^node:/, "")));
const fail = (code: string, message: string): never => { throw new Error(`${code}: ${message}`); };
const plainId = (id: string) => id.replace(/[?#].*$/, "");
function checkSpecifier(source: string): string | undefined {
  if (/\.node(?:[?#]|$)/i.test(source)) fail("APLG_NATIVE_ADDON", "Native addons cannot enter a plugin browser bundle.");
  if (/^(?:@tauri-apps\/|@ai-switch\/tauri-plugin-runtime\/host(?:[/?#]|$)|@ai-switch\/tauri-plugin-devkit(?:[/?#]|$))/.test(source)) fail("APLG_HOST_IMPORT", "Host/devkit/Tauri APIs are forbidden in plugin code.");
  const normalized = source.replaceAll("\\", "/");
  if (/(?:^|\/)node_modules\/(?:@tauri-apps\/|@ai-switch\/tauri-plugin-devkit\/|@ai-switch\/tauri-plugin-runtime\/(?:dist\/)?host(?:\/|$))/.test(normalized)) fail("APLG_HOST_IMPORT", "Installed host/private entry paths cannot bypass plugin import policy.");
  if (aliases.has(source)) return aliases.get(source);
  const candidate = plainId(source); const bare = candidate.replace(/^node:/, "");
  if (source.startsWith("node:") || builtins.has(bare) || isBuiltin(candidate)) fail("APLG_UNSUPPORTED_NODE_MODULE", `Unsupported plugin Node module: ${JSON.stringify(source)}.`);
}

export function nodeAliases(): Plugin {
  let runtimeRoot = ""; let server = false;
  function runtimeCode(id: string) {
    const path = plainId(id); if (!runtimeRoot || !isAbsolute(path)) return false;
    const within = relative(runtimeRoot, path);
    return !!within && !isAbsolute(within) && !within.startsWith("..");
  }
  return {
    name: "aplg:node-aliases", enforce: "pre",
    config(config) {
      if (config.build?.ssr) return;
      // The runtime already ships shared browser ESM chunks. Re-optimizing each
      // subpath can duplicate the plugin singleton and hides the resolved files.
      return { optimizeDeps: { exclude: ["@ai-switch/tauri-plugin-runtime"] } };
    },
    configResolved(config) {
      server = !!config.build.ssr;
      if (!server) runtimeRoot = dirname(realpathSync(createRequire(join(config.root, "package.json")).resolve("@ai-switch/tauri-plugin-runtime/package.json")));
    },
    async resolveId(source, importer, options) {
      if (server || options.ssr || this.environment?.config.consumer === "server") return null;
      const target = checkSpecifier(source);
      if (!target) return null;
      const result = await this.resolve(target, importer, { skipSelf: true });
      if (!result || result.external || !runtimeCode(result.id)) fail("APLG_RUNTIME_RESOLUTION", "The adapter must resolve to the plugin project's installed runtime package.");
      return result;
    },
    generateBundle(_options, bundle) {
      if (server || this.environment?.config.consumer === "server") return;
      // User externals can bypass resolve/transform hooks. No unresolved Node or
      // host imports are allowed in the plugin's final static/dynamic chunk graph.
      for (const item of Object.values(bundle)) if (item.type === "chunk") {
        for (const imported of [...item.imports, ...item.dynamicImports]) {
          if (checkSpecifier(imported)) fail("APLG_EXTERNAL_NODE_IMPORT", "A Node adapter was externalized instead of bundled.");
        }
      }
    },
    transform(code, id, options) {
      if (server || options?.ssr || this.environment?.config.consumer === "server") return null;
      checkSpecifier(id);
      // This exact virtual module is generated by the pinned bundler, not plugin
      // input. Its Node-only binary helper is tree-shaken from browser output.
      if (id === "\0rolldown/runtime.js" || runtimeCode(id) || !/\.[cm]?[jt]sx?$/.test(plainId(id))) return null;
      checkNodeUsage(code, plainId(id), checkSpecifier);
      return null;
    },
  };
}
